### ISSUE TITLE
Synchronizing PotionEffects not working

### ISSUE THREAD

**Issue by BrainStone** [AuraDevelopmentTeam/InvSync#12]
#### Issue Description:
The newly added feature of potion synchronzing is not working because of another sponge bug.

#### What happens:
The potion effects get stored in the database but not put on the player.

#### What you expected to happen:
That the potion effects get put on the player correctly.

#### Steps to reproduce:

1. Give self potion effect.
2. Leave server
3. Edit player data to change effect
4. Log back in to notice that the effect did not get overridden by database

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- InvSync: 0.5.32
- Sponge: spongevanilla-1.11.2-7.0.0-BETA-263

See SpongePowered/SpongeCommon#1276

**Comment by BrainStone** [comment]
According to the issue it should work now.

**Comment by bluelightning32** [comment]
I hit this bug. Here's the stacktrace I got:
```
[18:48:21] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task invsync-S-46 owned by Plugin{id=invsync, name=Inventory Sync, version=0.6.19.280-DEV, description=This plugin synchronizes the player inventory with a database, url=https://github.com/AuraDevelopmentTeam/InvSync, authors=[The_BrainStone], source=/home/minecraft/dd_ss/node1/server/./mods/plugins/InvSync-0.6.19.280-DEV.jar}, but an error occured.
java.lang.NullPointerException: value
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[minecraft_server.1.12.2.jar:?]
        at org.spongepowered.common.data.MemoryDataView.set(MemoryDataView.java:232) ~[MemoryDataView.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.common.data.MemoryDataContainer.set(MemoryDataContainer.java:77) ~[MemoryDataContainer.class:1.12.2-2768-7.1.6-RC3596]
        at net.minecraft.potion.PotionEffect.toContainer(PotionEffect.java:587) ~[va.class:?]
        at org.spongepowered.common.data.MemoryDataView.setCollection(MemoryDataView.java:327) ~[MemoryDataView.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.common.data.MemoryDataView.set(MemoryDataView.java:278) ~[MemoryDataView.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.common.data.MemoryDataContainer.set(MemoryDataContainer.java:77) ~[MemoryDataContainer.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.common.data.MemoryDataContainer.set(MemoryDataContainer.java:42) ~[MemoryDataContainer.class:1.12.2-2768-7.1.6-RC3596]
        at world.jnc.invsync.util.serializer.module.PotionEffectsSyncModule.serialize(PotionEffectsSyncModule.java:23) ~[PotionEffectsSyncModule.class:0.6.19.280-DEV]
        at world.jnc.invsync.util.serializer.module.BaseSyncModule.serialize(BaseSyncModule.java:80) ~[BaseSyncModule.class:0.6.19.280-DEV]
        at world.jnc.invsync.util.serializer.PlayerSerializer.serializePlayer(PlayerSerializer.java:110) ~[PlayerSerializer.class:0.6.19.280-DEV]
        at world.jnc.invsync.event.PlayerEvents.savePlayer(PlayerEvents.java:177) ~[PlayerEvents.class:0.6.19.280-DEV]
        at world.jnc.invsync.event.PlayerEvents.loadPlayer(PlayerEvents.java:170) ~[PlayerEvents.class:0.6.19.280-DEV]
        at world.jnc.invsync.event.PlayerEvents.access$200(PlayerEvents.java:34) ~[PlayerEvents.class:0.6.19.280-DEV]
        at world.jnc.invsync.event.PlayerEvents$WaitingForPreviousServerToFinish.accept(PlayerEvents.java:210) ~[PlayerEvents$WaitingForPreviousServerToFinish.class:0.6.19.280-DEV]
        at world.jnc.invsync.event.PlayerEvents$WaitingForPreviousServerToFinish.accept(PlayerEvents.java:180) ~[PlayerEvents$WaitingForPreviousServerToFinish.class:0.6.19.280-DEV]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:183) ~[SchedulerBase.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:169) ~[SchedulerBase.class:1.12.2-2768-7.1.6-RC3596]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_201]
        at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:404) [SpongeMod.class:1.12.2-2768-7.1.6-RC3596]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_696_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:746) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:696) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:657) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```
