### ISSUE TITLE
Connection is not available, request timed out after 30000ms.

### ISSUE THREAD

**Issue by sergeycherepanov** [AuraDevelopmentTeam/InvSync#24]
#### Issue Description:
Some times InvSync can't connect to sql server and lose inventory. Manual connection is worked fine. 

#### Steps to reproduce:

1. Set `wait_timeout = 30` in my.cnf
2. Try to play more than one minute
3. Leave server

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- InvSync: 0.6.17
- Sponge: 1.10.2-2281-5.2.0-BETA-2558
- Other related mods: 

#### Full log on pastebin: 

https://pastebin.com/raw/tNBAFB0s

```
[11:34:40] [Server thread/ERROR] [invsync]: Reconnecting failed!
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548) ~[HikariPool.class:1.10.2-2281-5.2.0-BETA-2558]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186) ~[HikariPool.class:1.10.2-2281-5.2.0-BETA-2558]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145) ~[HikariPool.class:1.10.2-2281-5.2.0-BETA-2558]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83) ~[HikariDataSource.class:1.10.2-2281-5.2.0-BETA-2558]
        at world.jnc.invsync.util.database.DatabaseConnection.reconnect(DatabaseConnection.java:49) ~[DatabaseConnection.class:0.6.17]
        at world.jnc.invsync.util.database.DatabaseConnection.verifyConnection(DatabaseConnection.java:65) [DatabaseConnection.class:0.6.17]
        at world.jnc.invsync.util.database.DataSource.saveInventory(DataSource.java:77) [DataSource.class:0.6.17]
        at world.jnc.invsync.event.PlayerEvents.savePlayer(PlayerEvents.java:163) [PlayerEvents.class:0.6.17]
        at world.jnc.invsync.event.PlayerEvents.onPlayerLeave(PlayerEvents.java:59) [PlayerEvents.class:0.6.17]
        at org.spongepowered.common.event.listener.DisconnectListener_PlayerEvents_onPlayerLeave51.handle(Unknown Source) [?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.10.2-2281-5.2.0-BETA-2558]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2558]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:297) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2558]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2558]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2558]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) [SpongeImpl.class:1.10.2-2281-5.2.0-BETA-2558]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onDisconnectHandler$zhf000(NetHandlerPlayServer.java:2284) [me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:802) [me.class:?]
        at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:455) [eo.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213) [md.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[11:34:40] [Server thread/WARN] [com.zaxxer.hikari.pool.ProxyConnection]: HikariPool-1 - Connection org.mariadb.jdbc.MariaDbConnection@1bbd1537 marked as broken because of SQLSTATE(08), ErrorCode(-1)
```

**Comment by BrainStone** [comment]
That is in fact weird. I'll try looking into it.

**Comment by BrainStone** [comment]
@SergeyCherepanov Could you try the latest BETA (https://ore.spongepowered.org/BrainStone/Inventory-Sync/versions/0.6.19.241-DEV) and see if it's still an issue there?

This seems to be related to #32.

@DownPower That's because mod inventories aren't supported yet. (Except for baubles in the latest beta.)
I'd recommend you opening a whole new issue for the backpack mod you want this plugin to work with.

**Comment by BrainStone** [comment]
Since there hasn't been any response I'll close this issue. If it persits, just reply here and I'll reopen
