### ISSUE TITLE
Food list not synced with latest solcarrot version

### ISSUE THREAD

**Issue by bluelightning32** [AuraDevelopmentTeam/InvSync#36]
#### Issue Description:
The solcarrot syncing doesn't work any more, because the com.cazsius.solcarrot.handler.HandlerCapability class was [renamed](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/commit/98db7602d3fa41fd984fec24052cc77b2407752f#diff-305ab7e694f734f7eccb1e62419e7850) to com.cazsius.solcarrot.handler.CapabilityHandler, but InvSync is still [using](https://github.com/AuraDevelopmentTeam/InvSync/blob/master/src/main/java/world/jnc/invsync/util/serializer/module/mod/SolCarrotSyncModule.java) the old name.

#### What happens:

```
[06:49:40] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task invsync-S-1 owned by Plugin{id=invsync, name=Inventory Sync, version=0.6.19.280-DEV, description=This plugin synchronizes the player inventory with a database, url=https://github.com/AuraDevelopmentTeam/InvSync, authors=[The_BrainStone], source=/home/minecraft/dd_ss/nodetest/server/./mods/plugins/InvSync-0.6.19.280-DEV.jar}, but an error occured.
java.lang.NoClassDefFoundError: com/cazsius/solcarrot/handler/HandlerCapability
        at world.jnc.invsync.util.serializer.module.mod.SolCarrotSyncModule$Helper.deserialize(SolCarrotSyncModule.java:93) ~[SolCarrotSyncModule$Helper.class:0.6.19.280-DEV]
        at world.jnc.invsync.util.serializer.module.mod.SolCarrotSyncModule$Helper.access$100(SolCarrotSyncModule.java:38) ~[SolCarrotSyncModule$Helper.class:0.6.19.280-DEV]
        at world.jnc.invsync.util.serializer.module.mod.SolCarrotSyncModule.deserialize(SolCarrotSyncModule.java:34) ~[SolCarrotSyncModule.class:0.6.19.280-DEV]
        at world.jnc.invsync.util.serializer.module.BaseSyncModule.deserialize(BaseSyncModule.java:86) ~[BaseSyncModule.class:0.6.19.280-DEV]
        at world.jnc.invsync.util.serializer.PlayerSerializer.deserializePlayer(PlayerSerializer.java:159) ~[PlayerSerializer.class:0.6.19.280-DEV]
        at world.jnc.invsync.event.PlayerEvents.loadPlayer(PlayerEvents.java:168) ~[PlayerEvents.class:0.6.19.280-DEV]
        at world.jnc.invsync.event.PlayerEvents.access$200(PlayerEvents.java:34) ~[PlayerEvents.class:0.6.19.280-DEV]
        at world.jnc.invsync.event.PlayerEvents$WaitingForPreviousServerToFinish.accept(PlayerEvents.java:210) ~[PlayerEvents$WaitingForPreviousServerToFinish.class:0.6.19.280-DEV]
        at world.jnc.invsync.event.PlayerEvents$WaitingForPreviousServerToFinish.accept(PlayerEvents.java:180) ~[PlayerEvents$WaitingForPreviousServerToFinish.class:0.6.19.280-DEV]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:183) ~[SchedulerBase.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:169) ~[SchedulerBase.class:1.12.2-2768-7.1.6-RC3596]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_201]
        at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:404) [SpongeMod.class:1.12.2-2768-7.1.6-RC3596]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_696_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:746) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:696) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:657) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: com.cazsius.solcarrot.handler.HandlerCapability
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
        ... 26 more
Caused by: java.lang.NullPointerException
```

#### What you expected to happen:

The simplest way to fix this is to have InvSync use CapabilityHandler and only work with recent versions of the solcarrot mod.

The alternative that I'm not in favor of is to clone the serializer so that one version works with the latest solcarrot and the other works with the old solcarrot.

**Comment by BrainStone** [comment]
Working on it. There was more stuff changed, which means I need to rewrite the serializer.  
But a working version should be out soon.

**Comment by bluelightning32** [comment]
It didn't work with the latest version:
```
[01:18:23] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Disconnect$Impl to Plugin{id=invsync, name=Inventory Sync, version=0.6.19.298-DEV, description=This plugin synchronizes the player inventory with a database, url=https://github.com/AuraDevelopmentTeam/InvSync, authors=[The_BrainStone], source=/home/minecraft/dd_ss/nodetest/server/./mods/plugins/InvSync-0.6.19.298-DEV.jar}
java.lang.ClassCastException: net.minecraft.nbt.NBTTagList cannot be cast to net.minecraft.nbt.NBTTagCompound
        at world.jnc.invsync.util.serializer.CapabilitySerializer.serializeCapability(CapabilitySerializer.java:14) ~[CapabilitySerializer.class:0.6.19.298-DEV]
        at world.jnc.invsync.util.serializer.CapabilitySerializer.serializeCapabilityToView(CapabilitySerializer.java:19) ~[CapabilitySerializer.class:0.6.19.298-DEV]
        at world.jnc.invsync.util.serializer.module.mod.SolCarrotSyncModule$Helper.serialize(SolCarrotSyncModule.java:37) ~[SolCarrotSyncModule$Helper.class:0.6.19.298-DEV]
        at world.jnc.invsync.util.serializer.module.mod.SolCarrotSyncModule$Helper.access$000(SolCarrotSyncModule.java:31) ~[SolCarrotSyncModule$Helper.class:0.6.19.298-DEV]
        at world.jnc.invsync.util.serializer.module.mod.SolCarrotSyncModule.serialize(SolCarrotSyncModule.java:22) ~[SolCarrotSyncModule.class:0.6.19.298-DEV]
        at world.jnc.invsync.util.serializer.module.BaseSyncModule.serialize(BaseSyncModule.java:80) ~[BaseSyncModule.class:0.6.19.298-DEV]
        at world.jnc.invsync.util.serializer.PlayerSerializer.serializePlayer(PlayerSerializer.java:125) ~[PlayerSerializer.class:0.6.19.298-DEV]
        at world.jnc.invsync.event.PlayerEvents.savePlayer(PlayerEvents.java:177) ~[PlayerEvents.class:0.6.19.298-DEV]
        at world.jnc.invsync.event.PlayerEvents.onPlayerLeave(PlayerEvents.java:87) ~[PlayerEvents.class:0.6.19.298-DEV]
        at org.spongepowered.common.event.listener.DisconnectListener_PlayerEvents_onPlayerLeave32.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:347) [SpongeModEventManager.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435) [SpongeModEventManager.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465) [SpongeEventManager.class:1.12.2-2768-7.1.6-RC3596]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:242) [SpongeImpl.class:1.12.2-2768-7.1.6-RC3596]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onDisconnectHandler$zja000(NetHandlerPlayServer.java:2418) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.onDisconnect(NetHandlerPlayServer.java:849) [pa.class:?]
        at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:457) [gw.class:?]
        at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:213) [oz.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by BrainStone** [comment]
Hm. I see the issue. I’ll try to fix it when I’m back on my computer.

**Comment by BrainStone** [comment]
Possibly fixed by 3bd76f023744fb563e8f1e526fcf5f05a2fca92c.  
Please check with this build: https://maven.aura-dev.team/repository/auradev-snapshots/world/jnc/invsync/InvSync/0.6.19.300-DEV/InvSync-0.6.19.300-DEV.jar

**Comment by bluelightning32** [comment]
I got a new error this time:
```
[12:50:35] [Server thread/INFO] [invsync]: Serializing data of bluelightning32 (2e15e144-51b9-4f4b-a495-74dc0765a409)
[12:50:35] [Server thread/INFO] [invsync]:      Module ModSolcarrot
[12:50:35] [Server thread/INFO] [invsync]:              isEnabled:      true
[12:50:35] [Server thread/INFO] [invsync]:              Permission:     invsync.sync.mod.solcarrot
[12:50:35] [Server thread/INFO] [invsync]:              hasPermission:  true
[12:50:35] [Server thread/INFO] [invsync]:              getSyncPlayer:  true
[12:50:35] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Disconnect$Impl to Plugin{id=invsync, name=Inventory Sync, version=0.6.19.300-DEV, description=This plugin synchronizes the player inventory with a database, url=https://github.com/AuraDevelopmentTeam/InvSync, authors=[The_BrainStone], source=/home/minecraft/dd_ss/nodetest/server/./mods/plugins/InvSync-0.6.19.300-DEV.jar}
java.lang.ClassCastException: Cannot cast net.minecraft.nbt.NBTTagString to net.minecraft.nbt.NBTTagCompound
        at java.lang.Class.cast(Class.java:3369) ~[?:1.8.0_201]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_201]
        at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:899) ~[?:1.8.0_201]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_201]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_201]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_201]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_201]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_201]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_201]
        at world.jnc.invsync.util.serializer.CapabilitySerializer.serializeCapabilityToViewList(CapabilitySerializer.java:40) ~[CapabilitySerializer.class:0.6.19.300-DEV]
        at world.jnc.invsync.util.serializer.module.mod.SolCarrotSyncModule$Helper.serialize(SolCarrotSyncModule.java:38) ~[SolCarrotSyncModule$Helper.class:0.6.19.300-DEV]
        at world.jnc.invsync.util.serializer.module.mod.SolCarrotSyncModule$Helper.access$000(SolCarrotSyncModule.java:32) ~[SolCarrotSyncModule$Helper.class:0.6.19.300-DEV]
        at world.jnc.invsync.util.serializer.module.mod.SolCarrotSyncModule.serialize(SolCarrotSyncModule.java:23) ~[SolCarrotSyncModule.class:0.6.19.300-DEV]
        at world.jnc.invsync.util.serializer.module.BaseSyncModule.serialize(BaseSyncModule.java:80) ~[BaseSyncModule.class:0.6.19.300-DEV]
        at world.jnc.invsync.util.serializer.PlayerSerializer.serializePlayer(PlayerSerializer.java:125) ~[PlayerSerializer.class:0.6.19.300-DEV]
        at world.jnc.invsync.event.PlayerEvents.savePlayer(PlayerEvents.java:177) ~[PlayerEvents.class:0.6.19.300-DEV]
        at world.jnc.invsync.event.PlayerEvents.onPlayerLeave(PlayerEvents.java:87) ~[PlayerEvents.class:0.6.19.300-DEV]
```

**Comment by BrainStone** [comment]
Possibly fixed by 7c789463efd8a9c1da6bbee1f78ec8ed33359d7c.
Please check with this build: https://maven.aura-dev.team/repository/auradev-snapshots/world/jnc/invsync/InvSync/0.6.19.301-DEV/InvSync-0.6.19.301-DEV.jar

**Comment by bluelightning32** [comment]
New error:
```
[14:13:18] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Disconnect$Impl to Plugin{id=invsync, name=Inventory Sync, version=0.6.19.301-DEV, description=This plugin synchronizes the player inventory with a database, url=https://github.com/AuraDevelopmentTeam/InvSync, authors=[The_BrainStone], source=/home/minecraft/dd_ss/nodetest/server/./mods/plugins/InvSync-0.6.19.301-DEV.jar}
java.lang.NoSuchMethodError: net.minecraft.nbt.NBTTagCompound.setTag(Ljava/lang/String;Lnet/minecraft/nbt/NBTBase;)V
        at world.jnc.invsync.util.serializer.CapabilitySerializer.serializeCapabilityToView(CapabilitySerializer.java:27) ~[CapabilitySerializer.class:0.6.19.301-DEV]
        at world.jnc.invsync.util.serializer.module.mod.SolCarrotSyncModule$Helper.serialize(SolCarrotSyncModule.java:38) ~[SolCarrotSyncModule$Helper.class:0.6.19.301-DEV]
        at world.jnc.invsync.util.serializer.module.mod.SolCarrotSyncModule$Helper.access$000(SolCarrotSyncModule.java:32) ~[SolCarrotSyncModule$Helper.class:0.6.19.301-DEV]
        at world.jnc.invsync.util.serializer.module.mod.SolCarrotSyncModule.serialize(SolCarrotSyncModule.java:23) ~[SolCarrotSyncModule.class:0.6.19.301-DEV]
        at world.jnc.invsync.util.serializer.module.BaseSyncModule.serialize(BaseSyncModule.java:80) ~[BaseSyncModule.class:0.6.19.301-DEV]
        at world.jnc.invsync.util.serializer.PlayerSerializer.serializePlayer(PlayerSerializer.java:125) ~[PlayerSerializer.class:0.6.19.301-DEV]
        at world.jnc.invsync.event.PlayerEvents.savePlayer(PlayerEvents.java:177) ~[PlayerEvents.class:0.6.19.301-DEV]
        at world.jnc.invsync.event.PlayerEvents.onPlayerLeave(PlayerEvents.java:87) ~[PlayerEvents.class:0.6.19.301-DEV]
```

**Comment by BrainStone** [comment]
That direct issue was fixed by 304c8dfc12e3a8d10a05ee0c13dd9b2fe1f9a55a.
And the follow up issue by 1a0f81c2129ac904e6501ef4142874ee35cca126.

Now build 303 should be good: https://maven.aura-dev.team/repository/auradev-snapshots/world/jnc/invsync/InvSync/0.6.19.303-DEV/InvSync-0.6.19.303-DEV.jar

**Comment by bluelightning32** [comment]
It worked!
```
[16:11:05] [Server thread/INFO] [invsync]: {"potion_effects":{"data":[]},"mod.cyclicmagic":{"crafting_capability":false,"inventory":[],"inventory_capability":false},"mod.baubles":{"data":[]},"mod.spiceoflife":{"data":{"spiceoflifeHistory":{"History":{"Foods":[{"WorldTime":101762587,"Hunger":1,"PlayerTime":1875162,"Saturation":0.05,"id":"harvestcraft:hazelnutitem","Count":14,"Damage":0},{"WorldTime":101762620,"Hunger":1,"PlayerTime":1875195,"Saturation":0.05,"id":"harvestcraft:hazelnutitem","Count":13,"Damage":0},{"WorldTime":101762653,"Hunger":1,"PlayerTime":1875228,"Saturation":0.05,"id":"harvestcraft:hazelnutitem","Count":12,"Damage":0},{"WorldTime":101762685,"Hunger":1,"PlayerTime":1875260,"Saturation":0.05,"id":"harvestcraft:hazelnutitem","Count":11,"Damage":0},{"WorldTime":101762718,"Hunger":1,"PlayerTime":1875293,"Saturation":0.05,"id":"harvestcraft:hazelnutitem","Count":10,"Damage":0},{"WorldTime":134467621,"Hunger":16,"PlayerTime":2088729,"Saturation":0.8,"id":"harvestcraft:delightedmealitem","Count":1,"Damage":0}]}}}},"game_mode":{"data":"minecraft:survival"},"health":{"data":20.0},"ender_chest":{"data":[]},"inventory":{"selectedSlot":0,"inventory":[{"slot":0,"stack":{"ContentVersion":1,"ItemType":"minecraft:iron_pickaxe","Count":1,"UnsafeDamage":1,"UnsafeData":{"pickletweaks":{"BlocksBroken":1}}}},{"slot":1,"stack":{"ContentVersion":1,"ItemType":"fluidtank:blocktank2","Count":1,"UnsafeDamage":1,"UnsafeData":{"BlockEntityTag":{"tier":{"string":"Copper"},"tank":{"FluidName":"methane","Amount":1000,"capacity":32000}}}}},{"slot":36,"stack":{"ContentVersion":1,"ItemType":"minecraft:iron_boots","Count":1,"UnsafeDamage":113}},{"slot":37,"stack":{"ContentVersion":1,"ItemType":"minecraft:iron_leggings","Count":1,"UnsafeDamage":99,"UnsafeData":{"ench":[{"lvl":2,"id":34}]}}},{"slot":38,"stack":{"ContentVersion":1,"ItemType":"minecraft:chainmail_chestplate","Count":1,"UnsafeDamage":165,"UnsafeData":{"ench":[{"lvl":1,"id":3}]}}},{"slot":39,"stack":{"ContentVersion":1,"ItemType":"minecraft:iron_helmet","Count":1,"UnsafeDamage":153}}]},"experience":{"experience_since_level":21,"experience_level":8},"version":1,"hunger":{"saturation":6.0,"food_level":16},"mod.solcarrot":{"data":["minecraft:carrot@0"]}}
```

**Comment by bluelightning32** [comment]
I spoke too soon. The food list is serialized and deserialized, but it doesn't get applied.

As shown in the previous comment, I ate a carrot. The next time I logged in, the debug line showed that carrot:
```
[11:16:28] [Server thread/INFO] [invsync]: {"mod.solcarrot":{"data":["minecraft:carrot@0"]},"potion_effects":{"data":[]},"mod.cyclicmagic":{"crafting_capability":false,"inventory":[],"inventory_capability":false},"mod.baubles":{"data":[]},"mod.spiceoflife":{"data":{"spiceoflifeHistory":{"History":{"Foods":[{"WorldTime":101762587,"Hunger":1,"PlayerTime":1875162,"Saturation":0.05,"id":"harvestcraft:hazelnutitem","Count":14,"Damage":0},{"WorldTime":101762620,"Hunger":1,"PlayerTime":1875195,"Saturation":0.05,"id":"harvestcraft:hazelnutitem","Count":13,"Damage":0},{"WorldTime":101762653,"Hunger":1,"PlayerTime":1875228,"Saturation":0.05,"id":"harvestcraft:hazelnutitem","Count":12,"Damage":0},{"WorldTime":101762685,"Hunger":1,"PlayerTime":1875260,"Saturation":0.05,"id":"harvestcraft:hazelnutitem","Count":11,"Damage":0},{"WorldTime":101762718,"Hunger":1,"PlayerTime":1875293,"Saturation":0.05,"id":"harvestcraft:hazelnutitem","Count":10,"Damage":0},{"WorldTime":134467621,"Hunger":16,"PlayerTime":2088729,"Saturation":0.8,"id":"harvestcraft:delightedmealitem","Count":1,"Damage":0}]}}}},"game_mode":{"data":"minecraft:creative"},"health":{"data":24.0},"ender_chest":{"data":[]},"inventory":{"selectedSlot":8,"inventory":[{"stack":{"ContentVersion":1,"ItemType":"minecraft:iron_boots","UnsafeDamage":113,"Count":1},"slot":36},{"stack":{"ContentVersion":1,"ItemType":"minecraft:iron_leggings","UnsafeDamage":99,"Count":1,"UnsafeData":{"ench":[{"lvl":2,"id":34}]}},"slot":37},{"stack":{"ContentVersion":1,"ItemType":"minecraft:chainmail_chestplate","UnsafeDamage":165,"Count":1,"UnsafeData":{"ench":[{"lvl":1,"id":3}]}},"slot":38},{"stack":{"ContentVersion":1,"ItemType":"minecraft:iron_helmet","UnsafeDamage":153,"Count":1},"slot":39}]},"experience":{"experience_since_level":21,"experience_level":8},"version":1,"hunger":{"saturation":0.0,"food_level":0}}
[11:16:28] [Server thread/DEBUG] [invsync]: Preparing statement: UPDATE `invsync_inventories` SET Active = TRUE WHERE UUID = ? LIMIT 1
```

However, `/foodlist size` reported 0 foods eaten. I eat a pear, and then it reported 1 foods eaten. When I logged out, only the pear was serialized (the carrot was lost):
```
[11:21:25] [Server thread/INFO] [invsync]: {"mod.solcarrot":{"data":["harvestcraft:pearitem@0"]},"potion_effects":{"data":[]},"mod.cyclicmagic":{"crafting_capability":false,"inventory":[],"inventory_capability":false},"mod.baubles":{"data":[]},"mod.spiceoflife":{"data":{"spiceoflifeHistory":{"History":{"Foods":[{"WorldTime":136031198,"Hunger":1,"PlayerTime":2151611,"Saturation":0.05,"id":"harvestcraft:pearitem","Count":61,"Damage":0},{"WorldTime":136031231,"Hunger":1,"PlayerTime":2151644,"Saturation":0.05,"id":"harvestcraft:pearitem","Count":60,"Damage":0},{"WorldTime":136031264,"Hunger":1,"PlayerTime":2151677,"Saturation":0.05,"id":"harvestcraft:pearitem","Count":59,"Damage":0},{"WorldTime":136031297,"Hunger":1,"PlayerTime":2151710,"Saturation":0.05,"id":"harvestcraft:pearitem","Count":58,"Damage":0},{"WorldTime":136031330,"Hunger":1,"PlayerTime":2151743,"Saturation":0.05,"id":"harvestcraft:pearitem","Count":57,"Damage":0},{"WorldTime":136031363,"Hunger":1,"PlayerTime":2151776,"Saturation":0.05,"id":"harvestcraft:pearitem","Count":56,"Damage":0}]}}}},"game_mode":{"data":"minecraft:survival"},"health":{"data":18.399993896484375},"ender_chest":{"data":[]},"inventory":{"selectedSlot":0,"inventory":[{"slot":0,"stack":{"ContentVersion":1,"ItemType":"harvestcraft:pearitem","Count":55,"UnsafeDamage":0}},{"slot":36,"stack":{"ContentVersion":1,"ItemType":"minecraft:iron_boots","Count":1,"UnsafeDamage":113}},{"slot":37,"stack":{"ContentVersion":1,"ItemType":"minecraft:iron_leggings","Count":1,"UnsafeDamage":99,"UnsafeData":{"ench":[{"lvl":2,"id":34}]}}},{"slot":38,"stack":{"ContentVersion":1,"ItemType":"minecraft:chainmail_chestplate","Count":1,"UnsafeDamage":165,"UnsafeData":{"ench":[{"lvl":1,"id":3}]}}},{"slot":39,"stack":{"ContentVersion":1,"ItemType":"minecraft:iron_helmet","Count":1,"UnsafeDamage":153}}]},"experience":{"experience_since_level":21,"experience_level":8},"version":1,"hunger":{"saturation":0.4000000059604645,"food_level":5}}
```

Next time I logged in, my food list was 0 again.

**Comment by BrainStone** [comment]
Try this version: https://maven.aura-dev.team/repository/auradev-snapshots/world/jnc/invsync/InvSync/0.6.19.307-DEV/InvSync-0.6.19.307-DEV.jar
